# Generated by Django 4.2.5 on 2023-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('Talent', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('Birth_Date', models.DateField()),
            ],
        ),
    ]
