# Generated by Django 4.2.5 on 2023-10-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boys',
            name='Birth_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='boys',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boys',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
